site_name: Documentation
site_url: https://jarbashivemind.github.io/HiveMind-community-docs/
nav:
    - Home: index.md
    - About:
      - Quick start: 01_quickstart.md
      - Terminology: 02_terminology.md
      - Nested Hives: 15_nested.md
      - Plugins: 04_plugins.md
      - Configuration: config.md
    - Plugins:
      - Agents: agents.md
      - Binary: binary_plugins.md
      - Network: network_plugins.md
      - Database: db_plugins.md
    - Satellites:
      - Overview: satellites.md
      - Voice Satellite: 07_voicesat.md
      - Voice Relay: 07_voice_relay.md
      - Mic Satellite: 07_micsat.md
    - Integrations:
      - OpenVoiceOS Pipeline: pipeline.md
      - Matrix: 09_matrix.md
      - DeltaChat: 10_deltachat.md
      - Home Assistant: 07_homeassistant.md
    - Protocol:
      - Transport: 04_protocol.md
      - Binarization: 18_binarization.md
      - OVOS Messages: 13_mycroft.md
    - Security:
      - Database: 17_database.md
      - Pairing: 03_pairing.md
      - Permissions: 16_permissions.md
      - Handshake: 12_handshake.md
      - Encryption: 19_crypto.md
    - Developers:
      - Libraries: 11_devs.md
    - ChatGPT was here:
      - ELI5: gpt_eli5.md

theme: readthedocs
